name: Deploy Astro Blog to Server

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies and Build 🏗️
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Deploy to Server 🚀
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          # 请务必替换为你的 1Panel 真实网站路径
          TARGET: "/opt/1panel/apps/openresty/openresty/www/sites/www.bradom.cn/index"